# Site Settings
title: Enkya | A place to entertain nothing more than logic
email: bruce.bigirwenkya@andela.com
description: Some text about your blog.
baseurl: "/enkya" # the subpath of your site, e.g. /blog
url: "https://www.elbertbiggs360.github.io" # the base hostname & protocol for your site
google_analytics: "UA-XXXXXXXX-X"

# User Settings
username: elbertbiggs360
user_description: Open minded developer
disqus_username: elbertbiggs360

# Social Media
# Remove the item if you don't need it
github_username: elbertbiggs360
facebook_username: Elbert.Bruce.B
twitter_username: elbertbiggs360
instagram_username: elbertbiggs360
linkedin_username: the_sdet
medium_username: elbertbiggs360

# Build settings
markdown: kramdown
highlighter: rouge
permalink: /:title/

# Plugins
gems:
  - jemoji

# Links to include in menu navigation
# For external links add external: true
links:
  - title: Home
    url: /
  - title: About
    url: /about/
  - title: Contact
    url: /contact/

# Exclude my node related stuff
exclude: ['package.json', 'src', 'node_modules']
